export enum Cuisine {
  AFRICAN = "African",
  ASIAN = "Asian",
  AMERICAN = "American",
  BRITISH = "British",
  CAJUN = "Cajun",
  CARIBBEAN = "Caribbean",
  CHINESE = "Chinese",
  EASTERN_EUROPEAN = "Eastern European",
  ENGLISH = "English",
  EUROPEAN = "European",
  FRENCH = "French",
  GERMAN = "German",
  GREEK = "Greek",
  INDIAN = "Indian",
  IRISH = "Irish",
  ITALIAN = "Italian",
  JAPANESE = "Japanese",
  JEWISH = "Jewish",
  KOREAN = "Korean",
  LATIN_AMERICAN = "Latin American",
  MEDITERRANEAN = "Mediterranean",
  MEXICAN = "Mexican",
  MIDDLE_EASTERN = "Middle Eastern",
  NORDIC = "Nordic",
  SCOTTISH = "Scottish",
  SOUTH_AMERICAN = "South American",
  SOUTHERN = "Southern",
  SPANISH = "Spanish",
  THAI = "Thai",
  VIETNAMESE = "Vietnamese",
}

export const cuisineAsSelectOptions = Object.values(Cuisine).map((cuisine) => ({
  label: cuisine,
  value: cuisine,
}));
